version: '3.7'

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6380:6380'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
